// This file defines a RESTful web service endpoint in Java using Spring framework, which handles HTTP requests to get a list of all surveys and add new survey data
// to the database. The Survey class defines a database entity with fields representing survey data columns in the database table.

package com.surveymanagementsystem.models; // This line indicates that the class is part of the package named com.surveymanagementsystem.models
// Import required classes
import lombok.Getter;
import lombok.Setter;
import javax.persistence.*;
import java.util.List;
@Entity // This annotation indicates that the class is a database entity
// These annotations are from Lombok library and generate getter/setter methods for each
@Getter
@Setter
public class Survey {
    @Id // This annotation specifies that the field is the primary key for the entity
    @GeneratedValue(strategy = GenerationType.AUTO) // This annotation specifies that the primary key value will be automatically generated by the database
    private long id;
    // The following fields correspond to columns in the database table for this entity
    @Column
    private String firstName;
    @Column
    private String lastName;
    @Column
    private String address;
    @Column
    private String city;
    @Column
    private String state;
    @Column
    private String zip;
    @Column
    private String phoneNumber;
    @Column
    private String emailId;
    @Column
    private String surveyDate;
    @Column
    @ElementCollection(targetClass=String.class) // This annotation specifies that the field will be stored as a separate table in the database
    private List<String> checkboxValues;
    @Column
    private String platform;
    @Column
    private String recommend;
    @Column
    private String comments;
}
